# This workflow build and push a Docker container to Google Artifact Registry
# and deploy it on Cloud Run when a commit is pushed to the "master"
# branch.
name: "Build and Deploy Backend to Cloud Run"

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: "startup-studi-case" # TODO: update to your Google Cloud project ID
  REGION: "asia-southeast2" # TODO: update to your region
  SERVICE: "backend" # TODO: update to your service name

jobs:
  deploy:
    runs-on: "ubuntu-latest"

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332" # actions/checkout@v4

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@f112390a2df9932162083945e46d439060d66ec2" # google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Authorize Docker push"
        run: "gcloud auth configure-docker $REGION-docker.pkg.dev"

      # - name: 'Docker Auth'
      #   uses: 'docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567' # docker/login-action@v3
      #   with:
      #     username: 'oauth2accesstoken'
      #     password: '${{ steps.auth.outputs.auth_token }}'
      #     registry: '${{ env.REGION }}-docker.pkg.dev'

      - name: "Build and Push Container"
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/b2b-startup/${{ env.SERVICE }}:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"

      - name: "Deploy to Cloud Run"
        uses: "google-github-actions/deploy-cloudrun@33553064113a37d688aa6937bacbdc481580be17" # google-github-actions/deploy-cloudrun@v2
        with:
          service: "${{ env.SERVICE }}"
          region: "${{ env.REGION }}"
          image: "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/b2b-startup/${{ env.SERVICE }}:${{ github.sha }}"
          flags: '--port=3002 --allow-unauthenticated'

      - name: "Show output"
        run: |2-
          echo ${{ steps.deploy.outputs.url }}
